name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log in to Docker (if needed)
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build and test the Docker image
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test

      # Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-761018894024
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip